import React from "react";
import { v4 as uuidv4 } from "uuid";
import CardCompleta from "./CardCompleta";


const buzos = [
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo1.jpeg",
    titulo: "BUZO 1",
    color: "BLACK",
    off: 30,
    antiguo: 32000,
    precio: 20000,
    cuotas: "",
    ventas: 41,
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo2.jpeg",
    titulo: "BUZO 2",
    color: "WHITE",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 5,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo3.jpeg",
    titulo: "BUZO 3",
    color: "WHITE",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 40,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo4.jpeg",
    titulo: "BUZO 4",
    color: "BLACK",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 40,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo5.jpeg",
    titulo: "BUZO 5",
    color: "GREY",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 36,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo6.jpeg",
    titulo: "BUZO 6",
    color: "BLACK",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 38,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo7.jpeg",
    titulo: "BUZO 7",
    color: "GREY",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 10,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo8.jpeg",
    titulo: "BUZO 8",
    color: "WHITE",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 15,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo9.jpeg",
    titulo: "BUZO 9",
    color: "BLACK",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 12,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo10.jpeg",
    titulo: "BUZO 10",
    color: "BLACK",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 29,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo11.jpeg",
    titulo: "BUZO 11",
    color: "BLACK",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 35,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo12.jpeg",
    titulo: "BUZO 12",
    color: "WHITE",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 17,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo13.jpeg",
    titulo: "BUZO 13",
    color: "GREY",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 11,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: uuidv4(),
    img: "/img(buzos)/buzo14.jpeg",
    titulo: "BUZO 14",
    color: "BLACK",
    off: 30,
    antiguo: 40000,
    precio: 20000,
    ventas: 39,
    cuotas: "",
    sizes: ["s", "m", "l", "xl", "xxl"],
  },
];

const ListBuzo = () => {
  buzos.forEach((buzo) => {
    buzo.precio = buzo.antiguo - (buzo.antiguo * buzo.off) / 100;
  });

  return <CardCompleta data={buzos} categoryKey="titulo" />;
};

export default ListBuzo;
